disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_parameter_count

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_parameter_alignment_on_call

included:
  - tray-lang

excluded:
  - Pods
  - build
  - DerivedData
  - tray-langTests
  - tray-langUITests

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 600

cyclomatic_complexity:
  warning: 10
  error: 20

function_parameter_count:
  warning: 5
  error: 8 