name: Build Universal macOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Clean and prepare
      run: |
        echo "Current directory structure:"
        ls -la
        echo "Looking for Xcode project:"
        find . -name "*.xcodeproj" -type d
        echo "Cleaning project..."
        xcodebuild clean -project tray-lang.xcodeproj -scheme tray-lang
        echo "Project structure:"
        ls -la tray-lang/

    - name: Build for Intel
      run: |
        echo "Building for Intel architecture..."
        xcodebuild -project tray-lang.xcodeproj -scheme tray-lang -configuration Release -destination 'platform=macOS,arch=x86_64' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        mkdir -p build/Release
        echo "Looking for built app..."
        find . -name "tray-lang.app" -type d
        find ~/Library/Developer/Xcode/DerivedData -name "tray-lang.app" -type d
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "tray-lang.app" -type d | head -1)
        echo "Found app at: $APP_PATH"
        if [ -n "$APP_PATH" ]; then
          cp -r "$APP_PATH" build/Release/tray-lang-intel.app
          echo "Copied to build/Release/tray-lang-intel.app"
        else
          echo "ERROR: Could not find tray-lang.app"
          exit 1
        fi
        echo "Intel build completed"

    - name: Build for Apple Silicon
      run: |
        echo "Building for Apple Silicon architecture..."
        xcodebuild -project tray-lang.xcodeproj -scheme tray-lang -configuration Release -destination 'platform=macOS,arch=arm64' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        mkdir -p build/Release
        echo "Looking for built app..."
        find . -name "tray-lang.app" -type d
        find ~/Library/Developer/Xcode/DerivedData -name "tray-lang.app" -type d
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "tray-lang.app" -type d | head -1)
        echo "Found app at: $APP_PATH"
        if [ -n "$APP_PATH" ]; then
          cp -r "$APP_PATH" build/Release/tray-lang-arm64.app
          echo "Copied to build/Release/tray-lang-arm64.app"
        else
          echo "ERROR: Could not find tray-lang.app"
          exit 1
        fi
        echo "Apple Silicon build completed"

    - name: Create Universal Binary
      run: |
        # Create universal binary using lipo
        lipo -create build/Release/tray-lang-intel.app/Contents/MacOS/tray-lang build/Release/tray-lang-arm64.app/Contents/MacOS/tray-lang -output build/Release/tray-lang-universal
        
        # Copy the universal binary to the Intel app
        cp build/Release/tray-lang-universal build/Release/tray-lang-intel.app/Contents/MacOS/tray-lang
        
        # Create final universal app
        cp -r build/Release/tray-lang-intel.app build/Release/tray-lang-universal.app
        
        # List build artifacts
        ls -la build/Release/

    - name: Get version from project
      run: |
        VERSION=$(xcodebuild -project tray-lang.xcodeproj -showBuildSettings | grep "MARKETING_VERSION" | awk '{print $3}')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Building version: $VERSION"
        
    - name: Create signing script
      run: |
        cat > build/Release/sign-app.sh << 'EOF'
        #!/bin/bash
        # Tray Lang - Application Signing Script
        
        echo "Tray Lang - Application Signing Script"
        echo "======================================"
        
        # Check if app exists
        if [ ! -d "tray-lang-universal.app" ]; then
          echo "ERROR: tray-lang-universal.app not found in current directory"
          exit 1
        fi
        
        echo "1. Setting executable permissions..."
        chmod +x tray-lang-universal.app
        
        echo "2. Removing quarantine attributes..."
        xattr -cr tray-lang-universal.app
        
        echo "3. Signing application..."
        codesign --force --deep --sign - tray-lang-universal.app
        
        echo "4. Verifying signature..."
        codesign -dv tray-lang-universal.app
        
        echo "5. If macOS blocks execution, run:"
        echo "   sudo xattr -rd com.apple.quarantine tray-lang-universal.app"
        
        echo ""
        echo "Signing completed successfully!"
        echo "You can now drag the app to Applications folder."
        EOF
        
        chmod +x build/Release/sign-app.sh
        
    - name: Create DMG
      run: |
        # Install create-dmg if not available
        if ! command -v create-dmg &> /dev/null; then
          brew install create-dmg
        fi
        
        # Copy README to build directory
        cp README.md build/Release/
        
        # Create DMG with app, README and signing script
        create-dmg \
          --volname "Tray Lang v$VERSION" \
          --window-pos 200 120 \
          --window-size 800 500 \
          --icon-size 100 \
          --icon "tray-lang-universal.app" 175 120 \
          --icon "README.md" 375 120 \
          --icon "sign-app.sh" 575 120 \
          --hide-extension "tray-lang-universal.app" \
          --hide-extension "README.md" \
          --hide-extension "sign-app.sh" \
          --app-drop-link 175 300 \
          --text-size 12 \
          --text "README.md" 375 300 \
          --text "sign-app.sh" 575 300 \
          "build/Release/Tray-Lang-v$VERSION-Universal.dmg" \
          "build/Release/"

    - name: Upload Universal App
      uses: actions/upload-artifact@v4
      with:
        name: tray-lang-v${{ env.VERSION }}-universal
        path: |
          build/Release/tray-lang-universal.app
          build/Release/Tray-Lang-v${{ env.VERSION }}-Universal.dmg
          build/Release/README.md
          build/Release/sign-app.sh
        retention-days: 30

    - name: Create Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: Tray Lang v${{ env.VERSION }}
        body: |
          ## Tray Lang v${{ env.VERSION }}
          
          ### What's New
          - Universal binary for both Intel and Apple Silicon Macs
          - Automatic keyboard layout switching
          - Text transformation between Russian and English
          
          ### Installation
          1. Download and mount the DMG
          2. Run the signing script: `./sign-app.sh`
          3. Drag the app to Applications folder
          4. Grant accessibility permissions on first launch
          
          ### Files Included
          - `tray-lang-universal.app` - Universal macOS application
          - `README.md` - Installation and usage instructions
          - `sign-app.sh` - Automatic signing script
          
          ### System Requirements
          - macOS 14.0 or higher
          - Intel or Apple Silicon Mac
        files: |
          build/Release/Tray-Lang-v${{ env.VERSION }}-Universal.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
